#!/usr/bin/env python3
"""Generate include/meta/registry.hpp from every generated plugin header.

Scans include/**/*.hpp (excluding effect.hpp and include/meta/ itself),
extracts each plugin's namespace/class name via the same regex
check_compile.py uses to find what to instantiate, and derives its category
from the containing directory. Rerunning this is a full rescan-and-rewrite,
so the output can never drift out of sync with what's actually in include/.
"""

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INCLUDE_DIR = REPO_ROOT / "include"
META_DIR = INCLUDE_DIR / "meta"
OUTPUT = META_DIR / "registry.hpp"

CLASS_RE = re.compile(
    r"namespace\s+airwindohhs::(\w+)"
    r".*?"
    r"template\s*<\s*typename\s+(\w+)\s*>\s*class\s+(\w+)\s+final\s*:\s*public\s+Effect<\2>",
    re.DOTALL,
)


class PluginRef:
    def __init__(self, header, namespace, class_name, category):
        self.header = header
        self.namespace = namespace
        self.class_name = class_name
        self.category = category

    @property
    def slug(self):
        return self.namespace

    @property
    def rel_include(self):
        return self.header.relative_to(INCLUDE_DIR).as_posix()


def find_headers():
    return sorted(
        p
        for p in INCLUDE_DIR.rglob("*.hpp")
        if p.name != "effect.hpp" and p != INCLUDE_DIR / "meta.hpp" and META_DIR not in p.parents
    )


def collect_plugins():
    plugins = []
    unmatched = []
    for header in find_headers():
        match = CLASS_RE.search(header.read_text())
        if not match:
            unmatched.append(header)
            continue
        namespace, _template_param, class_name = match.groups()
        category = header.parent.name
        plugins.append(PluginRef(header, namespace, class_name, category))

    if unmatched:
        print(
            "headers that could not be parsed for a class (skipped, not included in registry):",
            file=sys.stderr,
        )
        for header in unmatched:
            print(f"  {header.relative_to(REPO_ROOT)}", file=sys.stderr)

    slugs = [p.slug for p in plugins]
    duplicates = {slug for slug in slugs if slugs.count(slug) > 1}
    if duplicates:
        raise SystemExit(f"duplicate plugin slugs found, load_by_name requires uniqueness: {sorted(duplicates)}")

    return sorted(plugins, key=lambda p: (p.category, p.slug))


def render(plugins):
    includes = "\n".join(f'#include "{p.rel_include}"' for p in plugins)

    factories = []
    for p in plugins:
        qualified_class = f"airwindohhs::{p.namespace}::{p.class_name}"
        factories.append(
            f"template <typename T>\n"
            f"inline std::unique_ptr<IPlugin<T>> make_{p.slug}()\n"
            f"{{\n"
            f"    return std::make_unique<PluginAdapter<T, {qualified_class}>>(\n"
            f"        airwindohhs::{p.namespace}::k_name, airwindohhs::{p.namespace}::k_tags,\n"
            f"        airwindohhs::{p.namespace}::k_short_description, airwindohhs::{p.namespace}::k_long_description);\n"
            f"}}"
        )
    factories_block = "\n\n".join(factories)

    entries = []
    for p in plugins:
        entries.append(
            "        { "
            f"airwindohhs::{p.namespace}::k_name, \"{p.slug}\", \"{p.category}\", "
            f"airwindohhs::{p.namespace}::k_tags, "
            f"airwindohhs::{p.namespace}::k_short_description, "
            f"airwindohhs::{p.namespace}::k_long_description, "
            f"static_cast<int>(airwindohhs::{p.namespace}::{p.class_name}<T>::kNumParameters), "
            f"&make_{p.slug}<T> }},"
        )
    entries_block = "\n".join(entries)

    return f"""// Generated by scripts/gen_meta.py -- do not edit by hand.
// Regenerate with: python3 scripts/gen_meta.py
#pragma once
#include <memory>
#include <string_view>
#include <vector>

#include "meta/iplugin.hpp"
#include "meta/plugin_adapter.hpp"
#include "meta/plugin_entry.hpp"

{includes}

namespace airwindohhs::meta {{

{factories_block}

template <typename T>
inline const std::vector<PluginEntry<T>>& all_plugins()
{{
    static const std::vector<PluginEntry<T>> table = {{
{entries_block}
    }};
    return table;
}}

}} // namespace airwindohhs::meta
"""


def main():
    plugins = collect_plugins()
    META_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(plugins))
    print(f"wrote {len(plugins)} plugins to {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
